---
spring.config.activate.on-profile: local
spring:
  redis:
    host: localhost
    port: 6379
---
spring.config.activate.on-profile: dev
spring:
  redis:
    host: localhost
    port: 6379
---
spring.config.activate.on-profile: prod
spring:
  redis:
    host:
    port:
