---
spring.config.activate.on-profile: local
spring:
  data:
    mongodb:
      uri : mongodb://127.0.0.1:27017/bridge
---
spring.config.activate.on-profile: dev
spring:
  data:
    mongodb:
      uri: mongodb+srv://bridgemongodb:<password>@bridge.maizcgk.mongodb.net/bridge?retryWrites=true&w=majority
---
spring.config.activate.on-profile: prod
spring:
  data:
    mongodb:
      uri:
